{% set name = "unicloud" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/unicloud/archive/{{ version }}.tar.gz
  sha256: f05a97f7f0e21139cb22825b53cfe0b3ae4f4e292be5dfc4f9be3eb8152d793c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - pip
    - poetry-core >=1.9.0
  run:
    - python >=3.12
    - loguru >=0.7.2
    - numpy >=2.1.2
    - pandas >=2.2.0
    - google-cloud-storage >=2.1.0
    - google-api-python-client >=2.119.0
    - boto3 >=1.34.54

test:
  imports:
    - unicloud
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Serapieum-of-alex/unicloud
  summary: 'Cloud storage utils package'
  description: |
    Google Cloud Storage/ AWS S3 utility package.
  license: GPL-3.0-only
  license_family: GPL-3
  license_file: LICENSE.md
  dev_url: https://github.com/Serapieum-of-alex/unicloud
  doc_url: https://unicloud.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
